site_name: '&lt;osp⚡&gt; Object Storage Proxy - Blazingly Fast Zero Latency Bucket Gateway'
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.share
    - content.code.copy

extra_css:
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - attr_list